version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
  mongodb:
    image: mongo:7.0.1-rc0-jammy
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}